# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26ae5e7423bfc71f1df0621412e279038fab1d94589447d2c70b43d6daf563a43d5ca0a05530b2ccd6713e94c1eb494120077f2365c2e218433e03e1011375f8

test:
  secret_key_base: 476a705f14ae5081a251190566498d1282582ebada25d5dfaf405ce74fd5ebe54a2e0f7e6a9274e76cb1c131a57b66b40367d8c90be3db431af98dee1b0f2730

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
